import SiteLink from "@/components/site-link";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { categories } from "@/data/site";
import { sitePath } from "@/data/paths";
import { pageMetadata } from "@/data/metadata";
import "./about.css";

export const metadata = pageMetadata("About FRUNORIA", "Fruit and botanical ingredient sourcing: explore FRUNORIA’s product focus and approach to selection, packaging and quality documentation.");
const focus = [
  {id:"frozen-berries", text:"IQF raspberries and blueberries for product-specific processing and sourcing discussions."},
  {id:"dried-fruits", text:"Dried lemon and orange slices, with cut, appearance and intended use at the centre of selection."},
  {id:"flowers-herbs", text:"Dried rose flowers and raspberry leaf tea, with botanical identity and material form to review."},
  {id:"fruit-tea-blends", text:"Fruit infusions and botanical combinations, discussed against the actual ingredient declaration."},
  {id:"tea-bags", text:"Filled tea-bag directions, with contents, bag materials and packing requirements considered together."},
];

export default function AboutPage() {
  return <><SiteHeader /><main id="main" className="about-page">
    <section className="shell ab-intro"><div><span className="eyebrow">Our focus</span><h1>About <em>FRUNORIA</em></h1></div><div className="ab-intro-copy"><h2>Fruit &amp; Botanical Ingredients for Food and Beverage Businesses</h2><p>FRUNORIA focuses on fruit and botanical ingredients for food and beverage sourcing, covering frozen berries, dried fruits, floral ingredients and tea products.</p><p>We connect ingredient selection with application, packaging and documentation questions. Whether you are comparing a single ingredient or preparing a private label brief, the starting point is the product your team needs to make.</p></div></section>
    <figure className="shell ab-main-image"><img src={sitePath("/images/about-contact/v1/about-brand.webp")} width={1672} height={941} alt="Illustrative ingredient composition with frozen raspberries and blueberries, dried citrus and flowers in separate dishes" fetchPriority="high" /><figcaption>Illustrative Concept</figcaption></figure>
    <section className="shell ab-focus ab-section" aria-labelledby="product-focus"><div><span className="eyebrow">01 / The ingredient range</span><h2 id="product-focus">Our Product <em>Focus</em></h2><p>Five connected ranges. A clear starting point for your next ingredient brief.</p><SiteLink className="text-link" href="/products">Explore all products <span aria-hidden="true">↗</span></SiteLink></div><div className="ab-directory">{focus.map((item,index) => {const category=categories.find(category=>category.id===item.id)!;return <SiteLink key={item.id} href={`/products?category=${item.id}`}><span className="ab-index">0{index+1}</span><div><h3>{category.name}</h3><p>{item.text}</p></div><span className="ab-arrow" aria-hidden="true">↗</span></SiteLink>;})}</div></section>
    <section className="ab-approach ab-section" aria-labelledby="approach-title"><div className="shell"><div className="ab-section-head"><span className="eyebrow">02 / A useful conversation</span><h2 id="approach-title">How We Approach <em>Your Project</em></h2></div><div className="ab-approach-grid"><figure><img src={sitePath("/images/about-contact/v1/about-selection.webp")} alt="Illustrative selection of dried citrus forms and flower samples with a scoop and blank sample cards" width={1448} height={1086} loading="lazy" /><figcaption>Illustrative Concept</figcaption></figure><div className="ab-approach-topics"><article><span className="mini-label">Selection</span><h3>Product Selection</h3><p>Start with the finished use, then identify the ingredient form and the sample checks that matter. Our product pages keep confirmed identity separate from the sizes, cuts and other requirements you want to discuss.</p><SiteLink className="text-link" href="/applications">Explore applications <span aria-hidden="true">↗</span></SiteLink></article><article><span className="mini-label">Project brief</span><h3>Packaging &amp; Project Requirements</h3><p>Keep the ingredient and the pack in the same brief. Specify your desired unit size, handling needs, artwork responsibilities and proposed quantity; the available route and order conditions need project-specific agreement.</p><SiteLink className="text-link" href="/private-label">Explore private label <span aria-hidden="true">↗</span></SiteLink></article><article><span className="mini-label">Documentation</span><h3>Quality &amp; Documentation</h3><p>Ask for evidence tied to the actual product, lot and supplying site. Our documentation request connects your ingredient and destination market with the files your purchasing or technical team needs to review.</p><SiteLink className="text-link" href="/quality">Explore Quality &amp; Compliance <span aria-hidden="true">↗</span></SiteLink></article></div></div></div></section>
    <section className="shell ab-audience ab-section" aria-labelledby="audience-title"><div><span className="eyebrow">03 / Project conversations</span><h2 id="audience-title">Built for <em>Professional Buyers</em></h2><p>From selecting an ingredient to preparing a branded product brief, start with the decisions your team needs to make. Explore samples, packing and documentation in one connected inquiry.</p></div><ul>{["Food & Beverage Brands","Ingredient Importers & Distributors","Food Processing Businesses","Tea & Private Label Project Teams"].map(name=><li key={name}><span aria-hidden="true">↗</span>{name}</li>)}</ul></section>
    <section className="ab-closing"><div className="shell"><div><span className="eyebrow">Start with your brief</span><h2>Let’s Discuss Your<br /><em>Ingredient Requirements</em></h2></div><div className="ab-closing-actions"><SiteLink className="button button-dark" href="/contact?source=about">Start an Inquiry <span aria-hidden="true">↗</span></SiteLink><SiteLink className="text-link" href="/products">Explore Products <span aria-hidden="true">↗</span></SiteLink></div></div></section>
  </main><SiteFooter /></>;
}
