import SiteLink from "@/components/site-link";
import { GuideBrowser } from "@/components/guide-browser";
import { getGuides, guideSummary, localGuidePreview } from "@/data/guides";
import { pageMetadata } from "@/data/metadata";
import { products, categories } from "@/data/site";
import { sitePath } from "@/data/paths";
export const metadata=pageMetadata("Insights & Buying Guides","Practical guides to ingredient selection, product specifications, packaging and sourcing documentation.");
export default function ResourcesPage(){return <div className="shell"><header className="guides-intro"><span className="eyebrow">Resources / The buying desk</span><h1>Insights &amp; <em>Buying Guides</em></h1><p>Practical guides to ingredient selection, product specifications, packaging and sourcing documentation.</p>{localGuidePreview && <p className="guide-preview-note">Local editorial preview · complete drafts awaiting review and publication approval.</p>}</header>
  <section className="sourcing-desk" aria-labelledby="sourcing-desk-title"><div className="sourcing-desk-heading"><div><span className="eyebrow">Tools for your next conversation</span><h2 id="sourcing-desk-title">Prepare a Clear <em>Sourcing Brief</em></h2></div><a className="button button-outline" href={sitePath("/downloads/frunoria-sourcing-checklist.txt")} download>Download Sourcing Checklist <span aria-hidden="true">↓</span></a></div><div className="sourcing-tools">
    <article><span className="mini-label">01 / Select</span><h3>Define the Ingredient</h3><p>Name the product, form and planned use. For a blend, identify the complete ingredient brief; for frozen berries, describe the fruit form needed for processing.</p><SiteLink className="text-link" href="/products">Compare product directions <span aria-hidden="true">↗</span></SiteLink></article>
    <article><span className="mini-label">02 / Evaluate</span><h3>Set the Review Criteria</h3><p>List the appearance, cut, preparation and packing points you want to evaluate. Use the sample checklist on each product page to start a focused sample discussion.</p><SiteLink className="text-link" href="/applications">Review application needs <span aria-hidden="true">↗</span></SiteLink></article>
    <article><span className="mini-label">03 / Document</span><h3>Connect the Evidence</h3><p>Identify your destination market, required specification and testing topics. Match records to the actual ingredient, sample or lot and supplying site.</p><SiteLink className="text-link" href="/quality#documentation-requests">Prepare a document request <span aria-hidden="true">↗</span></SiteLink></article>
  </div><p className="sourcing-file-note">Editable text checklist · a buyer preparation tool, not a product specification or test report.</p></section>
  <details className="sourcing-directory"><summary>Product Range Quick Reference <span aria-hidden="true">+</span></summary><p>Nine product directions across five ranges. Open a product for its identity, sample evaluation and documentation topics; listed directions do not establish stock, grades or fixed order terms.</p><div>{categories.map(category => <section key={category.id}><h3>{category.name}</h3><ul>{products.filter(product => product.categoryId === category.id).map(product => <li key={product.id}><SiteLink href={`/products/${product.id}`}>{product.name} <span aria-hidden="true">↗</span></SiteLink></li>)}</ul></section>)}</div></details>
  <GuideBrowser guides={getGuides().map(guideSummary)}/><aside className="guides-end"><div><span className="eyebrow">Start with your project</span><h2>Have a sourcing question?</h2><p>Share the ingredient, application or documentation you want to discuss.</p></div><SiteLink className="button button-dark" href="/contact?source=resources">Discuss Your Project <span aria-hidden="true">↗</span></SiteLink></aside></div>;}
